export const cars = [
  {
    id: "porsche-turbo-s",
    name: "PORSCHE TURBO S",
    brand: "porsche",
    year: "2022",
    color: "GREY",
    engine: "V6 - 3.0",
    seats: 4,
    doors: 2,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 445.99,
    image: "/images/cars/porsche-turbo-s.png",
  },
  {
    id: "audi-rs3",
    name: "AUDI RS3",
    brand: "audi",
    year: "2022",
    color: "RED",
    engine: "V6 - 2.5",
    seats: 5,
    doors: 4,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 445.99,
    image: "/images/cars/audi-rs3.png",
  },
  {
    id: "amg-gt-63-s",
    name: "AMG GT 63 S",
    brand: "mercedes",
    year: "2022",
    color: "WHITE",
    engine: "V8 - 4.0",
    seats: 4,
    doors: 2,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 445.99,
    image: "/images/cars/amg-gt-63-s.png",
  },
  {
    id: "purosangue",
    name: "PUROSANGUE",
    brand: "ferrari",
    year: "2023",
    color: "BLACK",
    engine: "V12 - 6.5",
    seats: 4,
    doors: 4,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 445.99,
    image: "/images/cars/purosangue.png",
  },
  {
    id: "porsche-turbo-s-2",
    name: "PORSCHE TURBO S",
    brand: "porsche",
    year: "2022",
    color: "SILVER",
    engine: "V6 - 3.0",
    seats: 4,
    doors: 2,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 445.99,
    image: "/images/cars/porsche-turbo-s2.png",
  },
  {
    id: "audi-rs3-2",
    name: "AUDI RS3",
    brand: "audi",
    year: "2022",
    color: "RED",
    engine: "V6 - 2.5",
    seats: 5,
    doors: 4,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 445.99,
    image: "/images/cars/audi-rs32.png",
  },
]
