export const cars = [
  {
    id: "ferrari-purosangue",
    name: "FERRARI PUROSANGUE",
    brand: "ferrari",
    year: "2024",
    color: "DARK GREY / YELLOW",
    engine: "V12",
    seats: 4,
    doors: 4,
    mileage: "200KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 12500,
    image: "/images/cars/ferrari-purosangue/ferrari-purosangue.png",
    images: [
      "/images/cars/ferrari-purosangue/ferrari-purosangue-1.jpeg",
      "/images/cars/ferrari-purosangue/ferrari-purosangue-2.jpeg",
      "/images/cars/ferrari-purosangue/ferrari-purosangue-3.jpeg",
      "/images/cars/ferrari-purosangue/ferrari-purosangue-4.jpeg",
      "/images/cars/ferrari-purosangue/ferrari-purosangue-5.jpeg",
      "/images/cars/ferrari-purosangue/ferrari-purosangue-6.jpeg",
      "/images/cars/ferrari-purosangue/ferrari-purosangue-7.jpeg",
      "/images/cars/ferrari-purosangue/ferrari-purosangue-8.jpeg",
    ]
  },
  {
    id: "ferrari-sf90",
    name: "FERRARI SF90",
    brand: "ferrari",
    year: "2024",
    color: "YELLOW",
    engine: "V8",
    seats: 2,
    doors: 2,
    mileage: "200KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 12500,
    image: "/images/cars/ferrari-sf90/ferrari-sf90.png",
    images: [
      "/images/cars/ferrari-sf90/ferrari-sf90-1.jpg",
      "/images/cars/ferrari-sf90/ferrari-sf90-2.jpg",
      "/images/cars/ferrari-sf90/ferrari-sf90-3.jpg",
      "/images/cars/ferrari-sf90/ferrari-sf90-4.jpg",
      "/images/cars/ferrari-sf90/ferrari-sf90-5.jpg",
      "/images/cars/ferrari-sf90/ferrari-sf90-6.jpg",
      "/images/cars/ferrari-sf90/ferrari-sf90-7.jpg",
    ]
  },
  {
    id: "ferrari-812-gts",
    name: "FERRARI 812 GTS",
    brand: "ferrari",
    year: "2024",
    color: "RED",
    engine: "V12",
    seats: 2,
    doors: 2,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 6000,
    image: "/images/cars/ferrari-812-gts/ferrari-812-gts.png",
    images: [
      "/images/cars/ferrari-812-gts/ferrari-812-gts-1.jpg",
      "/images/cars/ferrari-812-gts/ferrari-812-gts-2.jpg",
      "/images/cars/ferrari-812-gts/ferrari-812-gts-3.jpg",
      "/images/cars/ferrari-812-gts/ferrari-812-gts-4.jpg",
      "/images/cars/ferrari-812-gts/ferrari-812-gts-5.jpg",
    ]
  },
  {
    id: "ferrari-f8",
    name: "FERRARI F8",
    brand: "ferrari",
    year: "2024",
    color: "RED",
    engine: "V8",
    seats: 2,
    doors: 2,
    mileage: "200KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 3400,
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/images/cars/ferrari-f8/ferrari-f8-1.png",
      "/images/cars/ferrari-f8/ferrari-f8-2.png",
      "/images/cars/ferrari-f8/ferrari-f8-3.png",
    ]
  },
  {
    id: "ferrari-roma",
    name: "FERRARI ROMA",
    brand: "ferrari",
    year: "2024",
    color: "WHITE",
    engine: "V8",
    seats: 4, // 2+2
    doors: 2,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 2800,
    image: "/images/cars/ferrari-roma/ferrari-roma.png",
    images: [
      "/images/cars/ferrari-roma/ferrari-roma-1.png",
      "/images/cars/ferrari-roma/ferrari-roma-2.png",
      "/images/cars/ferrari-roma/ferrari-roma-3.png",
      "/images/cars/ferrari-roma/ferrari-roma-4.jpeg",
      "/images/cars/ferrari-roma/ferrari-roma-5.jpeg",
      "/images/cars/ferrari-roma/ferrari-roma-6.jpeg",
      "/images/cars/ferrari-roma/ferrari-roma-7.jpeg",
    ]
  },
  {
    id: "lamborghini-huracan-sto",
    name: "LAMBORGHINI HURACAN STO",
    brand: "lamborghini",
    year: "2024",
    color: "BLUE",
    engine: "V10",
    seats: 2,
    doors: 2,
    mileage: "200KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 4200,
    image: "/images/cars/lamborghini-huracan-sto/lamborghini-huracan-sto.png",
    images: [
      "/images/cars/lamborghini-huracan-sto/lamborghini-huracan-sto-1.jpg",
      "/images/cars/lamborghini-huracan-sto/lamborghini-huracan-sto-2.jpg",
      "/images/cars/lamborghini-huracan-sto/lamborghini-huracan-sto-3.jpg",
      "/images/cars/lamborghini-huracan-sto/lamborghini-huracan-sto-4.jpg",
      "/images/cars/lamborghini-huracan-sto/lamborghini-huracan-sto-5.webp",
      "/images/cars/lamborghini-huracan-sto/lamborghini-huracan-sto-6.webp",
      "/images/cars/lamborghini-huracan-sto/lamborghini-huracan-sto-7.webp",
      "/images/cars/lamborghini-huracan-sto/lamborghini-huracan-sto-8.jpeg",
      "/images/cars/lamborghini-huracan-sto/lamborghini-huracan-sto-9.jpeg",
      "/images/cars/lamborghini-huracan-sto/lamborghini-huracan-sto-10.jpeg",
    ]
  },
  {
    id: "lamborghini-aventador-svj",
    name: "LAMBORGHINI AVENTADOR SVJ",
    brand: "lamborghini",
    year: "2024",
    color: "WHITE",
    engine: "V12",
    seats: 2,
    doors: 2,
    mileage: "200KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 12500,
    image: "/images/cars/lamborghini-aventador-svj/lamborghini-aventador-svj.png",
    images: [
      "/images/cars/lamborghini-aventador-svj/lamborghini-aventador-svj-1.jpeg",
      "/images/cars/lamborghini-aventador-svj/lamborghini-aventador-svj-2.jpg",
      "/images/cars/lamborghini-aventador-svj/lamborghini-aventador-svj-3.jpeg",
      "/images/cars/lamborghini-aventador-svj/lamborghini-aventador-svj-4.jpg",
      "/images/cars/lamborghini-aventador-svj/lamborghini-aventador-svj-5.jpeg",
      "/images/cars/lamborghini-aventador-svj/lamborghini-aventador-svj-6.jpg",
      "/images/cars/lamborghini-aventador-svj/lamborghini-aventador-svj-7.jpeg",
    ]
  },
  {
    id: "lamborghini-evo-spyder",
    name: "LAMBORGHINI EVO SPYDER",
    brand: "lamborghini",
    year: "2024",
    color: "BLUE",
    engine: "V10",
    seats: 2,
    doors: 2,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 2800,
    image: "/images/cars/lamborghini-evo-spyder/lamborghini-evo-spyder.png",
    images: [
      "/images/cars/lamborghini-evo-spyder/lamborghini-evo-spyder-1.jpg",
      "/images/cars/lamborghini-evo-spyder/lamborghini-evo-spyder-2.jpg",
      "/images/cars/lamborghini-evo-spyder/lamborghini-evo-spyder-3.jpg",
      "/images/cars/lamborghini-evo-spyder/lamborghini-evo-spyder-4.jpeg",
      "/images/cars/lamborghini-evo-spyder/lamborghini-evo-spyder-5.jpeg",
      "/images/cars/lamborghini-evo-spyder/lamborghini-evo-spyder-6.jpeg",
    ]
  },
  {
    id: "lamborghini-evo-coupe",
    name: "LAMBORGHINI EVO COUPE",
    brand: "lamborghini",
    year: "2024",
    color: "BLUE",
    engine: "V10",
    seats: 2,
    doors: 2,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 2800,
    image: "/images/cars/lamborghini-evo-coupe/lamborghini-evo-coupe.png",
    images: [
      "/images/cars/lamborghini-evo-coupe/lamborghini-evo-coupe-1.jpeg",
      "/images/cars/lamborghini-evo-coupe/lamborghini-evo-coupe-2.jpeg",
      "/images/cars/lamborghini-evo-coupe/lamborghini-evo-coupe-3.jpeg",
      "/images/cars/lamborghini-evo-coupe/lamborghini-evo-coupe-4.jpeg",
    ]
  },
  {
    id: "lamborghini-urus",
    name: "LAMBORGHINI URUS",
    brand: "lamborghini",
    year: "2024",
    color: "BLUE",
    engine: "V10",
    seats: 5,
    doors: 4,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 2800,
    image: "/images/cars/lamborghini-urus/lamborghini-urus.png",
    images: [
      "/images/cars/lamborghini-urus/lamborghini-urus-1.jpeg",
      "/images/cars/lamborghini-urus/lamborghini-urus-2.jpeg",
      "/images/cars/lamborghini-urus/lamborghini-urus-3.jpeg",
      "/images/cars/lamborghini-urus/lamborghini-urus-4.jpeg",
      "/images/cars/lamborghini-urus/lamborghini-urus-5.jpeg",
      "/images/cars/lamborghini-urus/lamborghini-urus-6.jpeg",
    ]
  },
  {
    id: "audi-rs3-2025",
    name: "AUDI RS3 2025",
    brand: "audi",
    year: "2025",
    color: "GREY",
    engine: "2.5",
    seats: 5,
    doors: 4,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 1100,
    image: "/images/cars/audi-rs3-2025/audi-rs3-2025.png",
    images: [
      "/images/cars/audi-rs3-2025/audi-rs3-2025-1.png",
      "/images/cars/audi-rs3-2025/audi-rs3-2025-2.png",
      "/images/cars/audi-rs3-2025/audi-rs3-2025-3.png",
    ]
  },
  {
    id: "audi-r8",
    name: "AUDI R8",
    brand: "audi",
    year: "2024",
    color: "GREY",
    engine: "V10",
    seats: 2,
    doors: 2,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 1700,
    image: "/images/cars/audi-r8/audi-r8.png",
    images: [
      "/images/cars/audi-r8/audi-r8-1.jpg",
      "/images/cars/audi-r8/audi-r8-2.jpg",
      "/images/cars/audi-r8/audi-r8-3.jpg",
      "/images/cars/audi-r8/audi-r8-4.jpeg",
      "/images/cars/audi-r8/audi-r8-5.jpeg",
      "/images/cars/audi-r8/audi-r8-6.jpeg",
      "/images/cars/audi-r8/audi-r8-7.jpeg",
    ]
  },
  {
    id: "mercedes-g63-amg",
    name: "MERCEDES G 63 AMG",
    brand: "mercedes",
    year: "2024",
    color: "BLACK",
    engine: "V8",
    seats: 5,
    doors: 4,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 1700,
    image: "/images/cars/mercedes-g63-amg/mercedes-g63-amg.png",
    images: [
      "/images/cars/mercedes-g63-amg/mercedes-g63-amg-1.jpeg",
      "/images/cars/mercedes-g63-amg/mercedes-g63-amg-2.jpeg",
      "/images/cars/mercedes-g63-amg/mercedes-g63-amg-3.jpeg",
      "/images/cars/mercedes-g63-amg/mercedes-g63-amg-4.jpeg",
    ]
  },
  {
    id: "mercedes-sl-amg",
    name: "MERCEDES SL AMG",
    brand: "mercedes",
    year: "2024",
    color: "GREY",
    engine: "V8",
    seats: 4, // 2+2
    doors: 2,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 1700,
    image: "/images/cars/mercedes-sl-amg/mercedes-sl-amg.png",
    images: [
      "/images/cars/mercedes-sl-amg/mercedes-sl-amg-1.jpeg",
      "/images/cars/mercedes-sl-amg/mercedes-sl-amg-2.jpeg",
      "/images/cars/mercedes-sl-amg/mercedes-sl-amg-3.jpeg",
      "/images/cars/mercedes-sl-amg/mercedes-sl-amg-4.jpeg",
      "/images/cars/mercedes-sl-amg/mercedes-sl-amg-5.jpeg",
    ]
  },
  {
    id: "rolls-royce-cullinan",
    name: "ROLLS ROYCE CULLINAN",
    brand: "rolls-royce",
    year: "2024",
    color: "BLACK",
    engine: "V12",
    seats: 5,
    doors: 4,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 4100,
    image: "/images/cars/rolls-royce-cullinan/rolls-royce-cullinan.png",
    images: [
      "/images/cars/rolls-royce-cullinan/rolls-royce-cullinan-1.jpeg",
      "/images/cars/rolls-royce-cullinan/rolls-royce-cullinan-2.jpeg",
      "/images/cars/rolls-royce-cullinan/rolls-royce-cullinan-3.jpeg",
      "/images/cars/rolls-royce-cullinan/rolls-royce-cullinan-4.jpeg",
      "/images/cars/rolls-royce-cullinan/rolls-royce-cullinan-5.jpeg",
      "/images/cars/rolls-royce-cullinan/rolls-royce-cullinan-6.jpeg",
      "/images/cars/rolls-royce-cullinan/rolls-royce-cullinan-7.jpeg",
    ]
  },
  {
    id: "porsche-gt3-rs-weissach",
    name: "PORSCHE GT3 RS WEISSACH",
    brand: "porsche",
    year: "2024",
    color: "GREY",
    engine: "FLAT 6",
    seats: 2,
    doors: 2,
    mileage: "250KM",
    extraKmCost: 25,
    securityAmount: 0,
    dailyPrice: 7500,
    image: "/images/cars/porsche-gt3-rs-weissach/porsche-gt3-rs-weissach.png",
    images: [
      "/images/cars/porsche-gt3-rs-weissach/porsche-gt3-rs-weissach-1.jpeg",
      "/images/cars/porsche-gt3-rs-weissach/porsche-gt3-rs-weissach-2.jpeg",
      "/images/cars/porsche-gt3-rs-weissach/porsche-gt3-rs-weissach-3.jpeg",
      "/images/cars/porsche-gt3-rs-weissach/porsche-gt3-rs-weissach-4.jpeg",
    ]
  },
]
